.setup:
  image: node:20.19.3-bookworm-slim
  before_script:
    - corepack enable
    - corepack prepare pnpm@9.15.9 --activate
    - pnpm install --frozen-lockfile

.base_mobile:
  before_script:
    - cd apps/mobile
    - cp $KEY_PROPERTIES ./android/key.properties
    - echo $KEYSTORE_FILE | base64 -d > ./android/app/keystore.jks
    - flutter clean
    - flutter packages get
    - flutter pub run build_runner build --delete-conflicting-outputs
    - flutter pub run easy_localization:generate -S assets/translations -f keys -O lib/gen -o locale_keys.g.dart

.generate_dart_models_scripts:
  script:
    - CHANGE_ME_COMMAND_DART
