.common-ifs:
  on-merge-requests: &on-mr
    if: $CI_PIPELINE_SOURCE == "merge_request_event"
  is-schedule: &on-schedule
    if: $CI_PIPELINE_SOURCE == 'schedule'
  on-main: &on-main
    if: $CI_COMMIT_BRANCH == "main"
  on-api-staging-tag: &on-api-staging
    if: $CI_COMMIT_TAG =~ /^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)-api-staging$/
  on-api-prod-tag: &on-api-prod
    if: $CI_COMMIT_TAG =~ /^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)-api-prod$/
  on-mobile-staging-tag: &on-mobile-staging
    if: $CI_COMMIT_TAG =~ /^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)-mobile-staging$/
  on-mobile-prod-tag: &on-mobile-prod
    if: $CI_COMMIT_TAG =~ /^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)-mobile-prod$/

.common-rules:
  never: &never
    when: never
  no-schedule:
    - <<: *on-schedule
      <<: *never
  on-manual: &on-manual
    when: manual

.rules:merge-request:
  rules:
    - <<: *on-schedule
    - <<: *on-mr

.rules:development-api:
  rules:
    - <<: *on-schedule
      <<: *never
    - <<: *on-main
      changes:
        - apps/api/**/*

.rules:development-infra:
  rules:
    - <<: *on-schedule
      <<: *never
    - <<: *on-main
      changes:
          - .gitlab-ci.yml
          - infra/pipelines/**/*
          - infra/swarm/**/*

.rules:api-staging:
  rules:
    - <<: *on-api-staging

.rules:api-prod:
  rules:
    - <<: *on-api-prod

.rules:mobile-staging:
  rules:
    - <<: *on-mobile-staging

.rules:mobile-production:
  rules:
    - <<: *on-mobile-prod
